import { ArrowDown, ArrowUp, Eye, GripVertical, History, Plus, Rocket, Save } from 'lucide-react'
import { useEffect, useState, type FormEvent } from 'react'
import { Button, StatusBadge } from '../components/ui'
import { ErrorState, LoadingState } from '../components/CmsDialog'
import { useAsyncData } from '../hooks/useAsyncData'
import { getLandingWorkspace, messageFrom, publishLandingVersion, saveLandingDraft, type LandingWorkspace } from '../lib/showcase'
import type { Json, LandingSection } from '../lib/database.types'

const emptyContent = (content: Json): Record<string, Json | undefined> => content && typeof content === 'object' && !Array.isArray(content) ? content : {}
const sectionTemplates = [
  ['hero', 'Hero Section & Value Proposition'],
  ['featured_projects', 'Curated Featured Projects'],
  ['about', 'About JP Aluminium & Heritage Craftsmanship'],
  ['services', 'Services & Architectural Joinery'],
  ['materials', 'Materials & Finishes Showcase'],
  ['contact', 'Contact & Executive Consultation'],
] as const

export function LandingPage() {
  const { data, error, loading, reload } = useAsyncData(getLandingWorkspace)
  const [draft, setDraft] = useState<LandingWorkspace | null>(null)
  const [activeId, setActiveId] = useState<string | null>(null)
  const [dirty, setDirty] = useState(false)
  const [notice, setNotice] = useState('')
  const [saving, setSaving] = useState(false)
  useEffect(() => { if (data) { setDraft(data); setActiveId(data.sections[0]?.id ?? null); setDirty(false) } }, [data])
  const active = draft?.sections.find((section) => section.id === activeId)
  const updateSection = (patch: Partial<LandingSection>) => { setDraft((current) => current ? { ...current, sections: current.sections.map((section) => section.id === activeId ? { ...section, ...patch } : section) } : current); setDirty(true); setNotice('') }
  const moveSection = (index: number, direction: -1 | 1) => { if (!draft) return; const target = index + direction; if (target < 0 || target >= draft.sections.length) return; const sections = [...draft.sections]; [sections[index], sections[target]] = [sections[target], sections[index]]; setDraft({ ...draft, sections }); setDirty(true) }
  const addSection = () => { if (!draft) return; const template = sectionTemplates.find(([key]) => !draft.sections.some((section) => section.section_key === key)); if (!template) { setNotice('All approved homepage section types already exist.'); return } const now = new Date().toISOString(); const section: LandingSection = { id: crypto.randomUUID(), version_id: draft.version.id, section_key: template[0], title: template[1], description: null, content: {}, media_asset_id: null, is_visible: true, sort_order: draft.sections.length, created_at: now, updated_at: now, created_by: null, updated_by: null }; setDraft({ ...draft, sections: [...draft.sections, section] }); setActiveId(section.id); setDirty(true) }
  const save = async (event?: FormEvent) => { event?.preventDefault(); if (!draft) return; setSaving(true); setNotice(''); try { await saveLandingDraft(draft); setDirty(false); setNotice('Landing page draft saved securely.'); await reload() } catch (reason) { setNotice(messageFrom(reason)) } finally { setSaving(false) } }
  const publish = async () => { if (!draft || !window.confirm('Publish this landing page version and archive the current live version?')) return; setSaving(true); setNotice(''); try { await saveLandingDraft(draft); await publishLandingVersion(draft.version.id); setNotice('Landing page published.'); await reload() } catch (reason) { setNotice(messageFrom(reason)) } finally { setSaving(false) } }

  if (error) return <div className="page cms-page"><ErrorState message={error} retry={() => void reload()} /></div>
  if (loading || !draft) return <div className="page cms-page"><LoadingState label="Loading landing page draft…" /></div>
  const content = active ? emptyContent(active.content) : {}

  return <form className="page cms-page landing-page" onSubmit={save}>
    <div className="breadcrumbs">CMS Master Index <span>/</span> Landing Page</div>
    <div className="page-heading"><div><h1>Landing Page</h1><p>Manage homepage sections, featured projects, SEO, and controlled publishing.</p></div><div className="page-heading__actions"><Button type="submit" icon={<Save size={15} />} disabled={!dirty || saving}>{saving ? 'Saving…' : 'Save Draft'}</Button><Button type="button" variant="primary" icon={<Rocket size={15} />} onClick={() => void publish()} disabled={saving}>Publish Changes</Button></div></div>
    {notice && <div className="settings-notice" role="status">{notice}</div>}
    <section className="publish-strip"><div><StatusBadge status={draft.version.status} /><strong>Draft version #{draft.version.version_number}</strong></div><p>Publishing uses the protected database function; publication status cannot be changed directly.</p><div><button type="button"><Eye size={14} />Preview in editor</button><button type="button"><History size={14} />{draft.history.length} versions</button></div></section>
    <section className="cms-section landing-sections"><div className="cms-section__heading"><div><h2>Homepage Sections</h2><p>Manage the order, visibility, and content of homepage sections.</p></div><Button type="button" icon={<Plus size={15} />} onClick={addSection}>Add Section</Button></div><div className="section-list">{draft.sections.map((section, index) => <article key={section.id} className={activeId === section.id ? 'active' : ''}><GripVertical size={17} /><span className="section-order">{String(index + 1).padStart(2, '0')}</span><button type="button" className="section-copy" onClick={() => setActiveId(section.id)}><strong>{section.title || section.section_key}</strong><small>{section.description || 'No description'}</small></button><span className={`visibility-label ${section.is_visible ? 'visible' : ''}`}>{section.is_visible ? 'Visible' : 'Hidden'}</span><button type="button" onClick={() => setActiveId(section.id)}>Edit</button><button type="button" onClick={() => { setActiveId(section.id); updateSection({ is_visible: !section.is_visible }) }}><Eye size={15} /></button><button type="button" onClick={() => moveSection(index, -1)} disabled={index === 0}><ArrowUp size={14} /></button><button type="button" onClick={() => moveSection(index, 1)} disabled={index === draft.sections.length - 1}><ArrowDown size={14} /></button></article>)}</div></section>
    {active ? <section className="cms-section editor-section"><div className="cms-section__heading"><div><span className="eyebrow">Active Section Editor</span><h2>{active.title || active.section_key}</h2><p>Configure public copy and structured content for this draft.</p></div><span className="mock-label">Draft</span></div><div className="settings-fields"><label className="field"><span>Section title</span><input value={active.title ?? ''} onChange={(event) => updateSection({ title: event.target.value })} /></label><label className="field"><span>Section key</span><input value={active.section_key} disabled /></label><label className="field field--wide"><span>Description</span><textarea value={active.description ?? ''} onChange={(event) => updateSection({ description: event.target.value })} /></label><label className="field field--wide"><span>Main heading</span><textarea value={String(content.heading ?? '')} onChange={(event) => updateSection({ content: { ...content, heading: event.target.value } })} /></label><label className="field field--wide"><span>Supporting copy</span><textarea value={String(content.body ?? '')} onChange={(event) => updateSection({ content: { ...content, body: event.target.value } })} /></label></div></section> : <div className="empty-state"><h2>No sections in this draft</h2><p>Add one of the approved homepage section types.</p></div>}
    <section className="cms-section featured-section"><div className="cms-section__heading"><div><h2>Curated Featured Projects</h2><p>Only published projects can be selected and the database verifies this again at publish time.</p></div></div><div className="featured-grid">{draft.projects.map((project) => { const selected = draft.featured.some((item) => item.project_id === project.id); return <button type="button" key={project.id} className={`material-card ${selected ? 'selected' : ''}`} onClick={() => { const featured = selected ? draft.featured.filter((item) => item.project_id !== project.id) : [...draft.featured, { version_id: draft.version.id, project_id: project.id, sort_order: draft.featured.length, display_title: project.title, display_description: project.summary }]; setDraft({ ...draft, featured }); setDirty(true) }}><strong>{project.title}</strong><span>{project.location || 'Location not set'}</span><small>{selected ? 'Featured — click to remove' : 'Click to feature'}</small></button>})}</div></section>
    <div className="landing-bottom-grid"><section className="cms-section"><div className="cms-section__heading"><div><h2>Homepage SEO &amp; Meta Information</h2><p>Search and social sharing metadata.</p></div></div><div className="settings-fields"><label className="field field--wide"><span>Meta Title</span><input value={draft.version.meta_title ?? ''} onChange={(event) => { setDraft({ ...draft, version: { ...draft.version, meta_title: event.target.value } }); setDirty(true) }} /></label><label className="field field--wide"><span>Meta Description</span><textarea value={draft.version.meta_description ?? ''} onChange={(event) => { setDraft({ ...draft, version: { ...draft.version, meta_description: event.target.value } }); setDirty(true) }} /></label></div></section><section className="cms-section"><div className="cms-section__heading"><div><h2>Publishing History &amp; Audit Trail</h2><p>Recent landing page versions.</p></div></div><div className="history-list">{draft.history.map((version) => <p key={version.id}><strong>v{version.version_number} ({version.status})</strong><span>{new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(version.updated_at))}</span></p>)}</div></section></div>
  </form>
}
